services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
    ports:
      - "3307:80"
    depends_on:
      - mysql
    networks:
      - mysql-phpmyadmin

  laravel:
    image: laravel-app
    container_name: laravel
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ${APP_PATH}/bootstrap/cache:/var/www/html/bootstrap/cache
      - ${APP_PATH}/.env:/var/www/html/.env
    networks:
      - mysql-phpmyadmin
    ports:
      - "28190:80"
    depends_on:
      - mysql

networks:
  mysql-phpmyadmin:
    driver: bridge
